volumes:
  portal_home:
    name: arcgis_portal_home
  portal_data:
    name: arcgis_portal_data
  server_home:
    name: arcgis_server_home
  server_data:
    name: arcgis_server_data
  datastore_data:
    name: arcgis_datastore

services:
  server:
    image: arcgis-server
    hostname: ${AGE_SERVER}
    build: 
      context: ./arcgis-server
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - ESRI_VERSION=${ESRI_VERSION}
      - AGS_USERNAME=${AGE_USERNAME}
      - AGS_PASSWORD=${AGE_PASSWORD} 
    ports:
      - "6080:6080"
      - "6443:6443"
    volumes:
      - ./ArcGISServer:/app/ArcGISServer:ro
      - ./ArcGISGISServer.prvc:/app/authorization.prvc:ro
      - server_home:/home/arcgis:rw
#      - server_config:/home/arcgis/server/usr/config-store
#      - server_data:/home/arcgis/server/usr/directories
#      - server_logs:/home/arcgis/server/usr/logs
    # Uncomment the next three lines to work in a shell environment for debugging.
    #entrypoint: /bin/bash
    #stdin_open: true
    #tty: true

  portal:
    image: arcgis-portal
    hostname: ${AGE_PORTAL}
    build:
      context: ./portal-for-arcgis
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - ESRI_VERSION=${ESRI_VERSION}
      - AGP_USERNAME=${AGE_USERNAME}
      - AGP_PASSWORD=${AGE_PASSWORD} 
      - PORTAL_CONTENT=/home/arcgis/content
    ports:
      - "7080:7080"
      - "7443:7443"
    volumes:
      - ./PortalForArcGIS:/app/PortalForArcGIS:ro
      - ./PortalForArcGIS.json:/app/portal_license.json:ro
      - portal_home:/home/arcgis:rw
      - portal_data:/home/arcgis/content:rw
      # This is a really bad place for our data
      # change the installer
      #- portal_data:/home/arcgis/portal/usr/arcgisportal:rw
    links:
      - server
      - datastore
    # Uncomment the next three lines to work in a shell environment for debugging.
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    
#  web-adaptor:
#    build: web-adaptor
#    image: arcgis-web-adaptor
#    ports:
#      - "80:80"
#      - "443:443"
#    links:
#      - "portal"
#      - "server"

  datastore:
    image: arcgis-datastore
    hostname: ${AGE_DATASTORE}
    build: 
      context: ./datastore
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - ESRI_VERSION=${ESRI_VERSION}
      - AGE_SERVER=${AGE_SERVER}
      - AGE_USERNAME=${AGE_USERNAME}
      - AGE_PASSWORD=${AGE_PASSWORD} 
    ports:
      - "2443:2443"
      - "9876:9876"
    volumes:
      - ./ArcGISDataStore_Linux:/app/ArcGISDataStore:ro
      - datastore_data:/home/arcgis/datastore
    links:
      - server
    # Uncomment the next three lines to work in a shell environment for debugging.
    #entrypoint: /bin/bash
    #stdin_open: true
    #tty: true

