volumes:
#
# *_home volumes are the /home/arcgis directories
# and the software for each service gets installed there.
#
# *_data volumes are where the data for each services gets stored.
#
  portal_home:
    name: arcgis_portal_home
  portal_data:
    name: arcgis_portal_data
  server_home:
    name: arcgis_server_home
  server_data:
    name: arcgis_server_data
  datastore_home:
    name: arcgis_datastore_home
  datastore_data:
    name: arcgis_datastore_data

services:
  server:
    image: arcgis-server
    hostname: ${GISSERVER}
    build: 
      context: ./server
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - ESRI_VERSION=${ESRI_VERSION}
      - AGS_USERNAME=${USERNAME}
      - AGS_PASSWORD=${PASSWORD} 
    ports:
      - "6080:6080"
      - "6443:6443"
    volumes:
      - ./GISServer_11.0:/app/ArcGISServer:ro
      - ./ArcGISGISServerStandard_ArcGISServer_1431202.prvc:/app/authorization.prvc:ro
      - server_home:/home/arcgis:rw
      - server_data:/home/arcgis/directories:rw
#      - server_config:/home/arcgis/server/usr/config-store
#      - server_logs:/home/arcgis/server/usr/logs
    # Uncomment the next three lines to work in a shell environment for debugging.
    entrypoint: /bin/bash
    stdin_open: true
    tty: true

# 2024-03-04 Not working on Portal right now
#  portal:
#    image: arcgis-portal
#    hostname: ${PORTAL}
#    build:
#      context: ./portal
#      dockerfile: Dockerfile
#    env_file: ./.env
#    environment:
#      - ESRI_VERSION=${ESRI_VERSION}
#      - AGP_USERNAME=${USERNAME}
#      - AGP_PASSWORD=${PASSWORD} 
#      - PORTAL_CONTENT=/home/arcgis/content
#    ports:
#      - "7080:7080"
#      - "7443:7443"
#    volumes:
#      - ./PortalForArcGIS:/app/PortalForArcGIS:ro
#      - ./PortalForArcGIS.json:/app/portal_license.json:ro
#      - portal_home:/home/arcgis:rw
#      - portal_data:/home/arcgis/content:rw
      #- portal_data:/home/arcgis/portal/usr/arcgisportal:rw
#    links:
#      - server
#      - datastore
    # Uncomment the next three lines to work in a shell environment for debugging.
#    entrypoint: /bin/bash
#    stdin_open: true
#    tty: true
    
#  web-adaptor:
#    build: web-adaptor
#    image: arcgis-web-adaptor
#    ports:
#      - "80:80"
#      - "443:443"
#    links:
#      - "portal"
#      - "server"

  datastore:
    image: arcgis-datastore
    hostname: ${DATASTORE}
    build: 
      context: ./datastore
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - ESRI_VERSION=${ESRI_VERSION}
      - AGE_SERVER=${GISSERVER}
      - AGS_USERNAME=${USERNAME}
      - AGS_PASSWORD=${PASSWORD} 
    ports:
      - "2443:2443"
      - "9876:9876"
    volumes:
      - ./ArcGISDataStore_Linux:/app/ArcGISDataStore:ro
      - datastore_home:/home/arcgis/datastore:rw
# where does this belong
#      - datastore_data:/home/arcgis/?????:rw
    links:
      - server
    # Uncomment the next three lines to work in a shell environment for debugging.
    entrypoint: /bin/bash
    stdin_open: true
    tty: true

